spring:
  profiles:
    active:
      default
          
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://172.19.19.14:8761/eureka/
  instance:
    prefer-ip-address: true